### ISSUE TITLE
Ubuntu: python install fails

### ISSUE THREAD

**Issue by rjalexa** [ajk77/SimpleEMRSystem#6]
```
bob@Ubuntu-1604-xenial-64-minimal:~/SimpleEMRSystem$ pip install -r requirements.txt
Defaulting to user installation because normal site-packages is not writeable
Collecting asgiref==3.2.7
  Downloading asgiref-3.2.7-py2.py3-none-any.whl (19 kB)
Collecting cycler==0.10.0
  Downloading cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
Collecting Django==3.0.7
  Downloading Django-3.0.7-py3-none-any.whl (7.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.5/7.5 MB 61.0 MB/s eta 0:00:00
Collecting joblib==0.13.2
  Downloading joblib-0.13.2-py2.py3-none-any.whl (278 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 278.9/278.9 kB 43.5 MB/s eta 0:00:00
Collecting kiwisolver==1.1.0
  Downloading kiwisolver-1.1.0-cp38-cp38-manylinux1_x86_64.whl (91 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 91.7/91.7 kB 19.2 MB/s eta 0:00:00
Collecting matplotlib==3.1.1
  Downloading matplotlib-3.1.1.tar.gz (37.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 37.8/37.8 MB 45.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting msgpack==1.0.0
  Downloading msgpack-1.0.0-cp38-cp38-manylinux1_x86_64.whl (303 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 303.5/303.5 kB 42.5 MB/s eta 0:00:00
Collecting mysqlclient==1.4.4
  Downloading mysqlclient-1.4.4.tar.gz (86 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.2/86.2 kB 17.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [13 lines of output]
      /bin/sh: 1: mysql_config: not found
      /bin/sh: 1: mariadb_config: not found
      /bin/sh: 1: mysql_config: not found
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-sknw4u0p/mysqlclient_8f772c100b724821bfb0013c1dec6337/setup.py", line 16, in <module>
          metadata, options = get_config()
        File "/tmp/pip-install-sknw4u0p/mysqlclient_8f772c100b724821bfb0013c1dec6337/setup_posix.py", line 61, in get_config
          libs = mysql_config("libs")
        File "/tmp/pip-install-sknw4u0p/mysqlclient_8f772c100b724821bfb0013c1dec6337/setup_posix.py", line 29, in mysql_config
          raise EnvironmentError("%s not found" % (_mysql_config_path,))
      OSError: mysql_config not found
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by ajk77** [comment]
This may help
https://stackoverflow.com/questions/5178292/pip-install-mysql-python-fails-with-environmenterror-mysql-config-not-found

**Comment by rjalexa** [comment]
Thanks a bunch for trying to help but lost access to that machine and will take some time to recreate a similar environment. Sorry

**Comment by ajk77** [comment]
No problem. Feel free to reopen this issue if you encounter it in the future.
